(1) What does "print" function really do?   It prints out how it looks when it prints out the list, but when it comes to words it prints out as word without ''. (2) about np.linspace. It will be useful for many times calculating. (3) questions about when to use np.zeros(). (4) Is NumPY only for array? Is array that important? (5) More about array vs. list

In [14]:
a="My"
b="List"
c='ABC'
my_list=[a,b,'is','great',c]
print(my_list)

['My', 'List', 'is', 'great', 'ABC']


In [8]:
my_list[0]

'My'

In [9]:
my_list[2]

'is'

In [10]:
my_list[-5]

'My'

In [11]:
my_list[-3]

'is'

In [16]:
print(my_list[-5])
print(my_list[2])
print('My')
print("My")
print(my_list)

My
is
My
My
['My', 'List', 'is', 'great', 'ABC']


In [2]:
number=[1,3.4,3.2,5.4,6.6]
number[1]=[6]
print(number)

[1, [6], 3.2, 5.4, 6.6]


In [18]:
number[1]=6
print(number)

[1, 6, 3.2, 5.4, 6.6]


In [19]:
number_2=number+[9,2]
print(number_2)

[1, 6, 3.2, 5.4, 6.6, 9, 2]


In [20]:
del(number_2[-2])
print(number_2)

[1, 6, 3.2, 5.4, 6.6, 2]


In [22]:
my_list1=[1,2,3,'my','list']
print(my_list1)

[1, 2, 3, 'my', 'list']


In [23]:
import numpy as np

In [24]:
number=[1,2,3,4,5]
my_array=np.array(number)
print(my_array)

[1 2 3 4 5]


In [25]:
new_array=np.array([1,2,3,4,5,6])
print(new_array)

[1 2 3 4 5 6]


In [27]:
A=100
r=.03
t=np.array([1,2,5,10,100])
growth=A*(1+r)**t
print(growth)

[ 103.          106.09        115.92740743  134.39163793 1921.86319809]


In [32]:
array=np.zeros(5)
print(array)

[0. 0. 0. 0. 0.]


In [33]:
A=100
r=.03
t=np.linspace(0,200,200)
growth=A*(1+r)**t
print(growth)

[  100.           103.01530042   106.1215212    109.32140387
   112.61777261   116.01353678   119.51169344   123.11533003
   126.82762708   130.65186105   134.59140716   138.64974242
   142.83044868   147.13721579   151.57384487   156.14425165
   160.85246992   165.70265511   170.69908796   175.84617827
   181.14846881   186.61063935   192.23751073   198.03404919
   204.0053707    210.15674549   216.49360271   223.02153521
   229.74630449   236.67384577   243.81027322   251.16188541
   258.73517078   266.53681346   274.57369911   282.852921
   291.3817863    300.16782251   309.21878412   318.5426594
   328.14767753   338.04231582   348.23530717   358.73564784
   369.55260532   380.69572656   392.17484639   404.00009616
   416.18191274   428.73104769   441.65857675   454.97590965
   468.69480015   482.82735641   497.38605169   512.38373538
   527.83364428   543.74941435   560.14509271   577.03515002
   594.43449329   612.35847904   630.82292681   649.84413314
   669.43888599   689.62447

In [34]:
A=100
r=.03
t=np.linspace(0,200,20)
growth=A*(1+r)**t
print(growth)

[  100.           136.49875214   186.31909335   254.32323742
   347.14804548   473.85275016   646.80309094   882.87814792
  1205.11765482  1644.97056063  2245.36428831  3064.8942345
  4183.54238446  5710.48314998  7794.73824081 10639.72043117
 14523.08561958 19823.83064274 27059.28145341 36935.58152156]
