# Python Homework #2: Lists and Arrays

This homework will give you a basic understanding of lists and arrays. Before completing this homework, make sure you have read everything under Week 2 in the Python Guide (sections 4-5.2.3).

## Q1) Lists

**(a)** Create a list with the numbers 1-10. Print the list.

In [58]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**(b)** Print out the number 5 from your list. *Remember, Python has 0 based counting.*

Your output should look like this:

5

In [19]:
print(numbers[4])

5


In [31]:
#mylist.reverse()
#mylist

In [37]:
numbers.reverse()
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**(c)** Print the number 10 from your list. *Remember, when you're subsetting lists, you can also count backwards.*

In [30]:
numbers.reverse()
print(numbers)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


**(d)** Add the number 11 to your list. Print the list.

Your output should look like this:

\[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11\]

In [61]:
numbers1 = numbers + [11]
print(numbers1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


**(e)** Take out the number 3 from the prevoius list and print a new one. You should now have a list that looks like this:

\[1, 2, 4, 5, 6, 7, 8, 9, 10, 11\]

In [60]:
del(numbers1[3])
print(numbers1)

[1, 2, 3, 5, 6, 7, 8, 9, 10, 11]


## Q2) Arrays

**(a)** Import NumPy as np

In [ ]:
import numpy as np

**(b)** Convert the list from the earlier section, **Q1e**, to an array. Print the new array. Your output should look like this:

\[1  2  4  5  6  7  8  9  10  11\]

In [62]:
array1 = np.array(numbers1)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11]


**(c)** Multiply the entire array by 10. Print your output.

In [64]:
print(array1 * 10)

[ 10  20  30  40  50  60  70  80  90 100 110]


**(d)** Create a new array named *intervals*. Go from 1 to 10 with 19 intervals total. Print your array. *Hint: you can use a linspace array as outlined in the Python Guide to do this.*

In [66]:
array2 = np.linspace(1,10,19)
print(array2)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


**(e)** Create a new array named *zeros* that contains 15 zeroes. Print your array. *Hint: research the np.zeros function on Google.*

In [67]:
array3 = np.zeros(15)
print(array3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Q3) Learning How to Solve Systems of Equations in Python

In Python, it is possible to solve a system of two or more equations. In preparation for this assignment and future exercises, you will learn how to solve a system of equations in Python. Follow the steps below to complete this exercise. 

**Review of Linear Algebra** 

In Econ 215, you learned the following formula can be used to find unknowns of a system of equations.
$$
Ax = b \ \ \ \ \ \ (1)
$$

The equation (1) can be manipulated and solved using rules from linear algebra to arrive at the following equation.
$$
x = A^{-1} b \ \ \ \ \ (2)
$$

Equation (2) says the unknowns to a system of equations can be solved for by taking the inverse of matrix A and multiplying it by the constants of an equation. 


 **Video**

With those formulas in mind, watch the following video as it will teach you how to solve systems of equations in Python. 
    
__[Click here to watch video]( https://youtu.be/44pAWI7v5Zk)__

  

**Solve the Equations**

Using the information from the video, solve the equations below using Python. Be sure to format your answers so they look nice.

__(a)__

\begin{align*}
3x  + 4y &= 10\\
2x + 3y &= 7 
\end{align*}

In [78]:
A = np.array([[3,4],[2,3]])
C = np.array([10,7])
Y = np.linalg.solve(A,C)
print(Y)
print('x = ','{:.0f}'.format(Y[0]), ',', 'y = ','{:.0f}'.format(Y[1]))

[2. 1.]
x =  2 , y =  1


__(b)__

\begin{align*}
x - 2y + 3z &= 7\\
2x + y + z &= 4\\
-3x + 2y - 2z &= -10
\end{align*}


In [77]:
A = np.array([[1,-2,3],[2,1,1],[-3,2,-2]])
C = np.array([7,4,-10])
Y = np.linalg.solve(A,C)
print(Y)
print('x = ','{:.0f}'.format(Y[0]), ',', 'y = ','{:.0f}'.format(Y[1]), ',', 'z = ','{:.0f}'.format(Y[2]))

[ 2. -1.  1.]
x =  2 , y =  -1 , z =  1


## Saving and Exporting

Save your notebook, name the file, download as an HTML file, and turn it in on Canvas.